#!/usr/bin/env ruby
#
# Copyright 2018, gRPC Authors All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This script updates the Xcode project generated by the Swift Package
# Manager to use the preferred indentation settings for this project.
#
require 'xcodeproj'
project_path = './SwiftGRPC.xcodeproj'
project = Xcodeproj::Project.open(project_path)

project.main_group.uses_tabs = '0'
project.main_group.tab_width = '2'
project.main_group.indent_width = '2'

project.save
